import fs from "node:fs";
import path from "node:path";

import { ENV_SPEC } from "../src/env";
import { PROJECT_ROOT, resolvePath } from "../src/utils/paths.utils";

const SCRIPT_PROJECT_PATH = path.relative(PROJECT_ROOT, __filename);
const ENV_EXAMPLE_PATH = resolvePath(PROJECT_ROOT, ".env.example");

const entries: string[] = [];

for (const [name, spec] of Object.entries(ENV_SPEC)) {
  const line = spec.example === undefined
    ? `${name}=`
    : `${name}='${spec.example}'`;

  const comment = spec.desc === undefined
    ? ""
    : `# ${spec.desc}`;

  const entry = `${comment}\n${line}`.trim();
  entries.push(entry);
}

const header = `# ENV EXAMPLE FILE AUTO-GENERATED BY ${SCRIPT_PROJECT_PATH}`;
const content = header + "\n\n" + entries.join("\n\n") + "\n";

fs.writeFileSync(ENV_EXAMPLE_PATH, content);
console.log(
  `${SCRIPT_PROJECT_PATH}: ` +
  `declared ${entries.length} environment variables in ${ENV_EXAMPLE_PATH}`,
);
