#!/bin/sh

set -e -x

npm run lint

if git diff --staged --name-only | grep -q '^src/'; then
    npm run build
fi

if ! git diff --quiet --staged src/env.ts; then
    npx ts-node scripts/update-env-example.ts
fi

git add .env.example
